---
:ems:
  :ems_google:
    :blacklisted_event_names: []
    :event_handling:
      :event_groups:
:ems_refresh:
  :gce:
    :inventory_collections:
      :saver_strategy: default
  :gce_network:
    :inventory_collections:
      :saver_strategy: default
:http_proxy:
  :gce:
    :host:
    :password:
    :port:
    :user:
:log:
  :level_gce: info
:workers:
  :ems_metrics_collector_worker_google:
    :inherits_from: ems_metrics_collector_worker
  :ems_refresh_worker_google:
    :inherits_from: ems_refresh_worker
  :ems_refresh_worker_google_network:
    :inherits_from: ems_refresh_worker
  :event_catcher_google:
    :inherits_from: event_catcher
    :poll: 15.seconds
